import {
  addClip,
  addMarker,
  addTrack,
  addTrackAt,
  newId,
  type Clip,
  type ID,
  type KeyframeTrack,
  type MediaAsset,
  type Project,
} from "@movie-desk/core";
import { MODE_PRESETS } from "./modes";
import { beatSnap, timelineBeats } from "./reconform";
import { planReframe } from "./reframe";
import type { AssetAnalysis, CutReason, EditPlan, MusicAnalysis } from "./types";

const AUTO_MARKER_COLOR = "#38d0c4";

// 재조립 전 정리 — 이전 생성물(AUTO 트랙 + 자동 마커)만 걷어낸다.
export const removeAutoGenerated = (project: Project): Project => ({
  ...project,
  timeline: {
    ...project.timeline,
    tracks: project.timeline.tracks.filter((t) => !t.name.startsWith("AUTO ")),
    markers: (project.timeline.markers ?? []).filter((m) => m.color !== AUTO_MARKER_COLOR),
  },
});

// Re-conform 강도 ① — 새 음악의 비트 그리드로 AUTO V 컷을 스냅하고 음악 베드를
// 교체한다. 수동으로 넣은 다른 트랙은 건드리지 않는다.
export const applyBeatSnapToProject = (
  project: Project,
  music: MusicAnalysis,
  musicAsset: MediaAsset,
  isPhotoAsset: (id: ID) => boolean,
): { project: Project; report: { snapped: number; requantized: number; skipped: number } } => {
  const track = project.timeline.tracks.find((t) => t.name === "AUTO V");
  if (!track || track.clips.length === 0)
    return { project, report: { snapped: 0, requantized: 0, skipped: 0 } };

  const ordered = [...track.clips].sort((a, b) => a.start - b.start);
  const { durations, report } = beatSnap({
    durations: ordered.map((c) => c.duration),
    photoFlags: ordered.map((c) => (c.kind === "media" ? isPhotoAsset(c.assetId) : false)),
    beats: timelineBeats(music, 0),
  });

  let cursor = 0;
  const rebuilt = ordered.map((c, i) => {
    const duration = durations[i]!;
    const next = { ...c, start: cursor, duration } as Clip;
    cursor += duration;
    return next;
  });

  const totalMs = cursor;
  const fade: KeyframeTrack = {
    target: "volume",
    keyframes: [
      { at: Math.max(0, Math.min(totalMs, music.durationMs) - 1500), value: 1, easing: "linear" },
      { at: Math.min(totalMs, music.durationMs), value: 0, easing: "linear" },
    ],
  };
  const musicClip: Clip = {
    kind: "media",
    id: newId(),
    assetId: musicAsset.id,
    start: 0,
    duration: Math.min(totalMs, music.durationMs),
    speed: 1,
    trimIn: 0,
    trimOut: Math.min(totalMs, music.durationMs),
    effects: [],
    keyframes: [fade],
    label: "자동 편집 음악",
  } as Clip;

  const tracks = project.timeline.tracks.map((t) => {
    if (t.name === "AUTO V") return { ...t, clips: rebuilt };
    if (t.name === "AUTO M") return { ...t, clips: [musicClip] };
    return t;
  });
  const hasMusicTrack = tracks.some((t) => t.name === "AUTO M");
  const withMusic = hasMusicTrack
    ? { ...project, timeline: { ...project.timeline, tracks } }
    : (() => {
        let p2: Project = { ...project, timeline: { ...project.timeline, tracks } };
        p2 = addTrack(p2, {
          kind: "audio",
          name: "AUTO M",
          height: 44,
          muted: false,
          solo: false,
          locked: false,
        });
        const mt = p2.timeline.tracks.at(-1)!;
        return addClip(p2, mt.id, musicClip);
      })();
  return { project: withMusic, report };
};

// Turn an EditPlan into project mutations. Pure (project in → project out) so
// the store can commit it as ONE undoable command and tests can assert on it.
// The generated content lands on fresh AUTO tracks; existing tracks are left
// untouched (the wizard normally runs on an empty timeline).

const KEN_SCALE = 1.12;
const PAN_X = 0.045;

const kenBurnsKeyframes = (
  kind: NonNullable<EditPlan["items"][number]["kenBurns"]>,
  durMs: number,
): {
  transform: { x: number; y: number; scale: number; rotation: number; opacity: number };
  tracks: KeyframeTrack[];
} => {
  const base = { x: 0, y: 0, scale: 1, rotation: 0, opacity: 1 };
  const lin = "linear" as const;
  switch (kind) {
    case "in":
      return {
        transform: base,
        tracks: [
          {
            target: "transform.scale",
            keyframes: [
              { at: 0, value: 1, easing: lin },
              { at: durMs, value: KEN_SCALE, easing: lin },
            ],
          },
        ],
      };
    case "out":
      return {
        transform: base,
        tracks: [
          {
            target: "transform.scale",
            keyframes: [
              { at: 0, value: KEN_SCALE, easing: lin },
              { at: durMs, value: 1, easing: lin },
            ],
          },
        ],
      };
    case "pan-l":
    case "pan-r": {
      const dir = kind === "pan-l" ? 1 : -1;
      return {
        transform: { ...base, scale: 1.08 },
        tracks: [
          {
            target: "transform.x",
            keyframes: [
              { at: 0, value: PAN_X * dir, easing: lin },
              { at: durMs, value: -PAN_X * dir, easing: lin },
            ],
          },
        ],
      };
    }
  }
};

export interface ApplyOptions {
  readonly plan: EditPlan;
  readonly assets: ReadonlyMap<ID, MediaAsset>;
  readonly music?: MusicAnalysis & { readonly opfsAssetId: ID };
  readonly summary?: string; // 여행 요약 카드 ("3일 · 5곳 · 420km")
  readonly analyses?: ReadonlyMap<ID, AssetAnalysis>; // P6 리프레임 얼굴 경로
  readonly formatReasons?: (reasons: readonly CutReason[]) => string;
}

export const applyPlanToProject = (project: Project, opts: ApplyOptions): Project => {
  const { plan } = opts;
  const preset = MODE_PRESETS[plan.mode];
  let p = project;
  const vertical = preset.aspect === "9:16";
  if (vertical) p = { ...p, resolution: { w: 1080, h: 1920 } };

  // Fresh AUTO tracks at the top of the stack (earlier index composites on
  // top): titles above the auto video, so chapter cards are never hidden.
  p = addTrackAt(
    p,
    { kind: "video", name: "AUTO V", height: 60, muted: false, solo: false, locked: false },
    0,
  );
  const videoTrack = p.timeline.tracks[0]!;
  const wantsTitles = plan.items.some((i) => i.chapter) || Boolean(opts.summary);
  let titleTrackId: ID | null = null;
  if (wantsTitles) {
    p = addTrackAt(
      p,
      { kind: "text", name: "AUTO T", height: 44, muted: false, solo: false, locked: false },
      0,
    );
    titleTrackId = p.timeline.tracks[0]!.id;
  }

  let cursor = 0;
  for (const item of plan.items) {
    const asset = opts.assets.get(item.assetId);
    if (!asset) continue;

    if (item.chapter) {
      p = addMarker(p, { at: cursor, label: item.chapter, color: "#38d0c4" });
      if (titleTrackId) {
        p = addClip(p, titleTrackId, {
          kind: "text",
          id: newId(),
          start: cursor,
          duration: Math.min(2600, Math.max(1800, item.durationMs)),
          speed: 1,
          effects: [],
          keyframes: [],
          text: item.chapter,
          font: "Inter, system-ui, sans-serif",
          size: 64,
          color: "#ffffff",
          align: "left",
          animIn: "slide-up",
          animOut: "fade",
          animMs: 400,
          transform: { x: -0.28, y: -0.6, scale: 1, rotation: 0, opacity: 1 },
        } as Clip);
      }
    }

    const ken =
      item.isPhoto && preset.kenBurns && item.kenBurns
        ? kenBurnsKeyframes(item.kenBurns, item.durationMs)
        : null;
    // 9:16 — cover-crop via fit:"fill" + face-following horizontal camera path.
    const reframe =
      vertical && !item.isPhoto
        ? planReframe(opts.analyses?.get(item.assetId), item.srcStartMs, item.durationMs)
        : null;

    p = addClip(p, videoTrack.id, {
      kind: "media",
      id: newId(),
      assetId: item.assetId,
      start: cursor,
      duration: item.durationMs,
      speed: 1,
      trimIn: item.isPhoto ? 0 : item.srcStartMs,
      trimOut: item.isPhoto ? item.durationMs : item.srcStartMs + item.durationMs,
      effects: [],
      keyframes: [...(ken ? ken.tracks : []), ...(reframe ? reframe.keyframes : [])],
      ...(ken ? { transform: ken.transform } : {}),
      ...(reframe?.transform ? { transform: reframe.transform } : {}),
      ...(vertical ? { fit: "fill" as const } : {}),
      ...(preset.keepNaturalAudio ? {} : { volume: 0 }),
      label:
        opts.formatReasons?.(item.reasons) ?? item.reasons.map((reason) => reason.code).join(" · "),
    } as Clip);
    cursor += item.durationMs;
  }

  // 여행 요약 카드 — 아웃트로에 "N일 · M곳 · D km".
  if (opts.summary && titleTrackId && cursor > 0) {
    const dur = 2500;
    p = addClip(p, titleTrackId, {
      kind: "text",
      id: newId(),
      start: Math.max(0, cursor - dur),
      duration: dur,
      speed: 1,
      effects: [],
      keyframes: [],
      text: opts.summary,
      font: "Inter, system-ui, sans-serif",
      size: 56,
      color: "#ffffff",
      align: "center",
      animIn: "fade",
      animOut: "fade",
      animMs: 500,
      transform: { x: 0, y: -0.35, scale: 1, rotation: 0, opacity: 1 },
    } as Clip);
  }

  // Music bed with a phrase-end fade.
  if (opts.music) {
    p = addTrack(p, {
      kind: "audio",
      name: "AUTO M",
      height: 44,
      muted: false,
      solo: false,
      locked: false,
    });
    const musicTrack = p.timeline.tracks.at(-1)!;
    const dur = Math.min(cursor, opts.music.durationMs);
    const fade: KeyframeTrack = {
      target: "volume",
      keyframes: [
        { at: Math.max(0, dur - 1500), value: 1, easing: "linear" },
        { at: dur, value: 0, easing: "linear" },
      ],
    };
    p = addClip(p, musicTrack.id, {
      kind: "media",
      id: newId(),
      assetId: opts.music.opfsAssetId,
      start: 0,
      duration: dur,
      speed: 1,
      trimIn: 0,
      trimOut: dur,
      effects: [],
      keyframes: [fade],
      label: "자동 편집 음악",
    } as Clip);
  }

  return p;
};
