"use client";

import { useMemo, useState } from "react";
import {
  Check,
  Copy,
  ExternalLink,
  Music,
  Pin,
  RefreshCw,
  Sparkles,
  Trash2,
  Wand2,
} from "lucide-react";
import { toast } from "sonner";
import type { ID } from "@movie-desk/core";
import { useProjectStore } from "@/stores/project-store";
import { useT } from "@/i18n/use-t";
import { cn } from "@/lib/cn";
import { saveSnapshot } from "@/persistence/snapshots";
import { doneAnalyses, useAnalysisStore } from "../analysis-store";
import { useAutoEditStore } from "../autoedit-store";
import { MODE_PRESETS, recommendLength, recommendMode, sunoPrompt } from "../modes";
import { generate } from "../generate";
import { analyzeMusic } from "../music";
import { applyBeatSnapToProject, removeAutoGenerated } from "../apply";
import { buildStory, goldenStats } from "../story";
import { enableSemantic, isSemanticEnabled } from "../semantic";
import type { EditMode } from "../types";

const MODES: readonly EditMode[] = ["highlight", "record", "shorts", "growth", "scenic"];

export function AutoEditPanel() {
  const t = useT();
  const project = useProjectStore((s) => s.project);
  const applyGenerated = useProjectStore((s) => s.applyGenerated);
  const entries = useAnalysisStore((s) => s.entries);
  const wiz = useAutoEditStore();
  const [confirmRerun, setConfirmRerun] = useState(false);
  const [semanticState, setSemanticState] = useState<"off" | "loading" | "on" | "failed">(
    isSemanticEnabled() ? "on" : "off",
  );

  const media = project.mediaLibrary;
  const audioAssets = media.filter((a) => a.kind === "audio");
  const visualAssets = media.filter((a) => a.kind !== "audio");

  // ── ② 분석 리포트 stats ────────────────────────────────────────────────
  const stats = useMemo(() => {
    const done = doneAnalyses(entries);
    let usableMs = 0;
    let smiley = 0;
    let facey = 0;
    let sampleCount = 0;
    let junkCount = 0;
    let failedCount = 0;
    let progressTotal = 0;
    for (const a of visualAssets) {
      const entry = entries[a.id];
      if (entry?.status === "failed") failedCount++;
      if (entry?.status === "done" || entry?.status === "failed") progressTotal += 1;
      else progressTotal += entry?.progress ?? 0;
      const r = done.get(a.id);
      if (!r) continue;
      if (r.junk.length > 0) {
        junkCount++;
        continue;
      }
      usableMs += a.kind === "image" ? 3000 : r.durationMs;
      for (const s of r.samples) {
        sampleCount++;
        if ((s.smile ?? 0) > 0.4) smiley++;
        if ((s.faceArea ?? 0) > 0.03) facey++;
      }
    }
    const doneCount = visualAssets.filter((a) => done.has(a.id)).length;
    const story = visualAssets.length > 0 ? buildStory(media) : null;
    const { goldenRatio } = goldenStats(media);
    return {
      doneCount,
      total: visualAssets.length,
      usableMs,
      junkCount,
      failedCount,
      progress: visualAssets.length > 0 ? progressTotal / visualAssets.length : 0,
      smileyRatio: sampleCount > 0 ? smiley / sampleCount : 0,
      faceRatio: sampleCount > 0 ? facey / sampleCount : 0,
      goldenRatio,
      story,
    };
  }, [entries, media, visualAssets]);

  const analysisSettled = stats.total > 0 && stats.doneCount + stats.failedCount === stats.total;
  const analysisReady = analysisSettled && stats.doneCount > 0;
  const rec = useMemo(
    () =>
      recommendMode({
        smileyRatio: stats.smileyRatio,
        faceRatio: stats.faceRatio,
        goldenRatio: stats.goldenRatio,
        usableMs: stats.usableMs,
      }),
    [stats],
  );

  const preset = MODE_PRESETS[wiz.mode];
  const modeLabel = (mode: EditMode) => t(`auto.mode.${mode}`);
  const recommendationReason = t(`auto.recommendReason.${rec.reason}`);
  const formatDuration = (ms: number) => {
    const seconds = Math.round(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    return minutes > 0
      ? `${minutes}:${String(seconds % 60).padStart(2, "0")}`
      : t("auto.durationSeconds", { n: seconds });
  };
  const manualEdited = wiz.appliedProject !== null && project !== wiz.appliedProject;

  // ── ④ 생성 / ⑤ 재조립 ─────────────────────────────────────────────────
  const runGenerate = async (isRerun: boolean) => {
    if (wiz.generating) return;
    wiz.setGenerating(true);
    setConfirmRerun(false);
    try {
      if (isRerun && manualEdited) {
        await saveSnapshot(project, t("auto.snapshotName"));
      }
      const analyses = doneAnalyses(useAnalysisStore.getState().entries);
      const result = await generate(useProjectStore.getState().project, analyses, {
        mode: wiz.mode,
        targetMs: wiz.targetMs,
        ...(wiz.musicAssetId ? { musicAssetId: wiz.musicAssetId } : {}),
        constraints: { pinned: wiz.pinned, excluded: wiz.excluded },
        mapTransitions: wiz.mapTransitions,
      });
      applyGenerated(t("auto.applyLabel"), (p) =>
        result.build(isRerun ? removeAutoGenerated(p) : p),
      );
      wiz.setResult({
        plan: result.plan,
        story: result.story,
        music: result.music ?? null,
        appliedProject: useProjectStore.getState().project,
      });
      toast.success(t("auto.generated", { n: result.plan.items.length }));
    } catch (err) {
      wiz.setGenerating(false);
      toast.error(`${t("auto.failed")}: ${err instanceof Error ? err.message : String(err)}`);
    }
  };

  const runBeatSnap = async () => {
    const assetId = wiz.musicAssetId;
    const asset = assetId ? media.find((a) => a.id === assetId) : undefined;
    if (!asset) return;
    const music = await analyzeMusic(asset.id, asset.opfsPath, asset.durationMs);
    if (!music) {
      toast.error(t("auto.musicAnalyzeFailed"));
      return;
    }
    const isPhoto = (id: ID) => media.find((a) => a.id === id)?.kind === "image";
    applyGenerated(t("auto.reconformLabel"), (p) => {
      const { project: next, report } = applyBeatSnapToProject(p, music, asset, isPhoto);
      toast.success(
        t("auto.reconformReport", {
          snapped: report.snapped,
          requantized: report.requantized,
          skipped: report.skipped,
        }),
      );
      return next;
    });
  };

  const assetName = (id: ID) => media.find((a) => a.id === id)?.name ?? id;

  return (
    <div className="flex h-full flex-col overflow-y-auto p-3 text-xs">
      {/* ② 분석 리포트 */}
      <Section title={t("auto.report")}>
        {stats.total === 0 ? (
          <p className="text-ink-3">{t("auto.noMedia")}</p>
        ) : (
          <>
            <div className="rounded-md border border-line bg-panel-2 p-2.5" aria-live="polite">
              <p className="break-keep font-medium leading-relaxed text-ink-1">
                {analysisSettled
                  ? stats.doneCount > 0
                    ? t("auto.reportReady", { duration: formatDuration(stats.usableMs) })
                    : t("auto.reportUnavailable")
                  : t("auto.reportScanning", { total: stats.total })}
              </p>
              <p className="mt-1 break-keep text-2xs leading-relaxed text-ink-3">
                {analysisSettled
                  ? stats.doneCount > 0
                    ? t("auto.reportReadyHint", {
                        done: stats.doneCount,
                        total: stats.total,
                      })
                    : t("auto.reportUnavailableHint")
                  : t("auto.reportScanningHint", {
                      done: stats.doneCount,
                      total: stats.total,
                    })}
              </p>
              {!analysisSettled && (
                <div
                  className="mt-2 h-1 overflow-hidden rounded-full bg-panel-3"
                  role="progressbar"
                  aria-label={t("auto.analysisProgress")}
                  aria-valuemin={0}
                  aria-valuemax={100}
                  aria-valuenow={Math.round(stats.progress * 100)}
                  tabIndex={0}
                >
                  <div
                    className="h-full rounded-full bg-accent transition-[width]"
                    style={{ width: `${Math.round(stats.progress * 100)}%` }}
                  />
                </div>
              )}
              {stats.failedCount > 0 && (
                <p className="mt-2 break-keep text-2xs leading-relaxed text-amber-200">
                  {t("auto.reportPartial", { failed: stats.failedCount })}
                </p>
              )}
            </div>
            {analysisReady && (
              <div className="mt-2 rounded-md border border-accent/30 bg-accent/10 p-2.5 text-ink-1">
                <div className="flex items-center gap-1.5 font-medium">
                  <Sparkles className="size-3.5 text-accent" />
                  {t("auto.recommend")}: {modeLabel(rec.mode)} ·{" "}
                  {formatDuration(recommendLength(stats.usableMs, rec.mode))}
                </div>
                <p className="mt-1 break-keep text-2xs leading-relaxed text-ink-3">
                  {recommendationReason}
                </p>
                <button
                  type="button"
                  className="btn-ghost mt-1.5 px-2 py-0.5 text-2xs"
                  onClick={() => {
                    wiz.setMode(rec.mode);
                    wiz.setTargetMs(recommendLength(stats.usableMs, rec.mode));
                  }}
                >
                  <Check className="size-3" /> {t("auto.applyRec")}
                </button>
              </div>
            )}
            <div className="mt-2 border-t border-line pt-1.5">
              <Row k={t("auto.analyzed")} v={`${stats.doneCount}/${stats.total}`} />
              <Row k={t("auto.usable")} v={formatDuration(stats.usableMs)} />
              {stats.junkCount > 0 && <Row k={t("auto.junk")} v={`${stats.junkCount}`} />}
              {stats.failedCount > 0 && (
                <Row k={t("auto.analysisFailed")} v={`${stats.failedCount}`} />
              )}
              {stats.goldenRatio > 0 && (
                <Row k={t("auto.golden")} v={`${Math.round(stats.goldenRatio * 100)}%`} />
              )}
              {stats.story && stats.story.days > 0 && (
                <Row k={t("auto.trip")} v={stats.story.summary} />
              )}
            </div>
          </>
        )}
      </Section>

      {/* ③ 방향 확정 */}
      <Section title={t("auto.direction")}>
        <div className="flex flex-wrap gap-1">
          {MODES.map((m) => (
            <button
              key={m}
              type="button"
              onClick={() => {
                wiz.setMode(m);
                wiz.setTargetMs(MODE_PRESETS[m].defaultTargetMs);
              }}
              className={cn(
                "rounded border px-2 py-1 text-2xs transition",
                wiz.mode === m
                  ? "border-accent bg-accent/15 text-ink-1"
                  : "border-white/10 text-ink-3 hover:text-ink-1",
              )}
            >
              {modeLabel(m)}
            </button>
          ))}
        </div>
        <div className="mt-2 flex items-center gap-2">
          <span className="w-14 shrink-0 text-ink-3">{t("auto.length")}</span>
          <input
            type="range"
            min={preset.targetRangeMs[0] / 1000}
            max={preset.targetRangeMs[1] / 1000}
            value={Math.round(wiz.targetMs / 1000)}
            onChange={(e) => wiz.setTargetMs(Number(e.target.value) * 1000)}
            className="flex-1 accent-[var(--accent,#38d0c4)]"
          />
          <span className="w-12 text-right font-mono text-ink-1">
            {formatDuration(wiz.targetMs)}
          </span>
        </div>
        <div className="mt-2 flex items-center gap-2">
          <Music className="size-3.5 shrink-0 text-ink-3" />
          <select
            value={wiz.musicAssetId ?? ""}
            onChange={(e) => wiz.setMusicAssetId((e.target.value || null) as ID | null)}
            className="min-w-0 flex-1 rounded bg-white/5 px-2 py-1 text-2xs text-ink-1 outline-none"
          >
            <option value="">{t("auto.noMusic")}</option>
            {audioAssets.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name}
              </option>
            ))}
          </select>
        </div>
        <div className="mt-1.5 flex flex-wrap items-center gap-1.5 text-2xs text-ink-3">
          <span>{t("auto.yalHint")}:</span>
          {preset.yalKeywords.map((k) => (
            <span key={k} className="rounded bg-white/5 px-1.5 py-0.5">
              {k}
            </span>
          ))}
          <a
            href="https://studio.youtube.com/channel/UC/music"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-0.5 text-accent hover:underline"
          >
            YouTube <ExternalLink className="size-3" />
          </a>
        </div>
        <button
          type="button"
          className="btn-ghost mt-1.5 px-2 py-0.5 text-2xs"
          onClick={() => {
            const tags =
              stats.story?.events.map((e) => e.label.split("— ")[1] ?? "").filter(Boolean) ?? [];
            void navigator.clipboard.writeText(sunoPrompt(wiz.mode, wiz.targetMs, tags));
            toast.success(t("auto.sunoCopied"));
          }}
        >
          <Copy className="size-3" /> {t("auto.sunoPrompt")}
        </button>
        <label className="mt-2 flex items-center gap-2 text-2xs text-ink-3">
          <input
            type="checkbox"
            checked={wiz.mapTransitions}
            onChange={(e) => wiz.setMapTransitions(e.target.checked)}
          />
          {t("auto.mapTransitions")}
        </label>
        <label className="mt-1.5 flex items-center gap-2 text-2xs text-ink-3">
          <input
            type="checkbox"
            checked={semanticState === "on" || semanticState === "loading"}
            disabled={semanticState === "loading"}
            onChange={async (e) => {
              if (!e.target.checked || semanticState === "on") return;
              setSemanticState("loading");
              const ok = await enableSemantic();
              setSemanticState(ok ? "on" : "failed");
              if (ok) {
                useAnalysisStore.getState().reset();
                useAnalysisStore
                  .getState()
                  .enqueue(useProjectStore.getState().project.mediaLibrary);
                toast.success(t("auto.semanticReady"));
              } else toast.error(t("auto.semanticFailed"));
            }}
          />
          {semanticState === "loading" ? t("auto.semanticLoading") : t("auto.semantic")}
        </label>
      </Section>

      {/* ④ 생성 */}
      <Section title={t("auto.generate")}>
        {wiz.plan === null ? (
          <button
            type="button"
            disabled={wiz.generating || stats.total === 0}
            onClick={() => void runGenerate(false)}
            className="btn-ghost w-full justify-center gap-2 border border-accent/40 bg-accent/10 py-2 text-xs font-medium text-ink-1 disabled:opacity-40"
          >
            <Wand2 className={cn("size-4", wiz.generating && "animate-pulse")} />
            {wiz.generating ? t("auto.generating") : t("auto.generateBtn")}
          </button>
        ) : (
          <div className="space-y-1.5">
            <Row k={t("auto.planItems")} v={`${wiz.plan.items.length}`} />
            <Row k={t("auto.planRejected")} v={`${wiz.plan.rejected.length}`} />
            {manualEdited && (
              <p className="rounded border border-amber-400/30 bg-amber-400/10 p-1.5 text-2xs text-amber-200">
                {t("auto.lockWarning")}
              </p>
            )}
            <div className="flex gap-1.5">
              <button
                type="button"
                disabled={wiz.generating}
                onClick={() => {
                  if (manualEdited && !confirmRerun) {
                    setConfirmRerun(true);
                    return;
                  }
                  void runGenerate(true);
                }}
                className={cn(
                  "btn-ghost flex-1 justify-center gap-1.5 border py-1.5 text-2xs",
                  confirmRerun ? "border-amber-400/60 text-amber-200" : "border-white/10",
                )}
              >
                <RefreshCw className={cn("size-3.5", wiz.generating && "animate-spin")} />
                {confirmRerun ? t("auto.rerunConfirm") : t("auto.rerun")}
              </button>
              {wiz.musicAssetId && (
                <button
                  type="button"
                  onClick={() => void runBeatSnap()}
                  className="btn-ghost flex-1 justify-center gap-1.5 border border-white/10 py-1.5 text-2xs"
                  title={t("auto.reconformTip")}
                >
                  <Music className="size-3.5" /> {t("auto.reconform")}
                </button>
              )}
            </div>
          </div>
        )}
      </Section>

      {/* ⑤ 리뷰 — 채택 + 탈락 후보 브라우저 */}
      {wiz.plan && (
        <>
          <Section title={`${t("auto.chosen")} (${wiz.plan.items.length})`}>
            <ul className="space-y-1">
              {wiz.plan.items.map((item, i) => (
                <li key={`${item.assetId}-${i}`} className="rounded bg-white/5 p-1.5">
                  <div className="flex items-center justify-between gap-2">
                    <span className="truncate text-ink-1">{assetName(item.assetId)}</span>
                    <span className="shrink-0 font-mono text-2xs text-ink-3">
                      {(item.durationMs / 1000).toFixed(1)}s
                    </span>
                  </div>
                  <p className="mt-0.5 truncate text-2xs text-ink-3">{item.reason}</p>
                  <button
                    type="button"
                    onClick={() => wiz.toggleExclude(item.assetId)}
                    className="mt-1 inline-flex items-center gap-1 text-2xs text-ink-3 hover:text-red-300"
                  >
                    <Trash2 className="size-3" /> {t("auto.exclude")}
                  </button>
                </li>
              ))}
            </ul>
          </Section>
          <Section title={`${t("auto.rejectedBrowser")} (${wiz.plan.rejected.length})`}>
            {wiz.plan.rejected.length === 0 ? (
              <p className="text-2xs text-ink-3">{t("auto.noRejected")}</p>
            ) : (
              <ul className="space-y-1">
                {wiz.plan.rejected.map((r, i) => (
                  <li key={`${r.assetId}-${i}`} className="rounded bg-white/5 p-1.5">
                    <div className="flex items-center justify-between gap-2">
                      <span className="truncate text-ink-1">{assetName(r.assetId)}</span>
                    </div>
                    <p className="mt-0.5 truncate text-2xs text-ink-3">{r.reason}</p>
                    <button
                      type="button"
                      onClick={() => wiz.togglePin(r.assetId)}
                      className={cn(
                        "mt-1 inline-flex items-center gap-1 text-2xs",
                        wiz.pinned.includes(r.assetId)
                          ? "text-accent"
                          : "text-ink-3 hover:text-ink-1",
                      )}
                    >
                      <Pin className="size-3" />
                      {wiz.pinned.includes(r.assetId) ? t("auto.pinned") : t("auto.pin")}
                    </button>
                  </li>
                ))}
              </ul>
            )}
            {(wiz.pinned.length > 0 || wiz.excluded.length > 0) && (
              <p className="mt-2 text-2xs text-ink-3">{t("auto.rerunHint")}</p>
            )}
          </Section>
        </>
      )}
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-3">
      <h3 className="mb-1.5 text-2xs font-semibold uppercase tracking-wider text-ink-3">{title}</h3>
      {children}
    </section>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex items-center justify-between py-0.5">
      <span className="text-ink-3">{k}</span>
      <span className="font-mono text-ink-1">{v}</span>
    </div>
  );
}
